name: Build
on: ["push", "pull_request"]
permissions:
  contents: read
jobs:
  test:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt && \
          python -m pip install -r requirements.dev.txt && \
          python -m pip install -r requirements.test.txt
      - name: Run linting
        run: ./lint.sh
      - name: Run type checker
        run: ./typecheck.sh
      - name: Run tests
        run: ./run-tests-with-coverage.sh
      - name: Archive coverage report
        uses: actions/upload-artifact@v4
        with:
          name: test-coverage-report
          path: coverage-html